# Welcome to Serverless!
#
# This file is the main config file for your service.
# It's very minimal at this point and uses default values.
# You can always add more config options for more control.
# We've included some commented out config examples here.
# Just uncomment any of them to get that config option.
#
# For full config options, check the docs:
#    docs.serverless.com
#
# Happy Coding!

service: resizePhotoNew

custom:
  stage: "${opt:stage, self:provider.stage}"

provider:
  name: aws
  runtime: nodejs10.x

  # you can overwrite defaults here
  #stage: dev
  profile: mobilepractice
  region: eu-west-1
  memorySize: 512
  timeout: 240
  environment: ${file(env.yml):${self:custom.stage}}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "logs:CreateLogGroup"
        - "logs:CreateLogStream"
        - "logs:PutLogEvents"
      Resource: "arn:aws:logs:*:*:*"
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource: { "Fn::Join" : ["", ["arn:aws:s3:::", { "Ref" : "ServerlessDeploymentBucket" } ] ]  }
    - Effect: "Allow"
      Action:
        - "s3:PutObject"
      Resource:
        Fn::Join:
          - ""
          - - "arn:aws:s3:::"
            - "Ref" : "ServerlessDeploymentBucket"
            - "/*"

functions:
  process:
    handler: handler.process
    events:
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpg
          existing: true
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .JPG
          existing: true
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .png
          existing: true
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .PNG
          existing: true
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .jpeg
          existing: true
      - s3:
          bucket: ${file(env.yml):${self:custom.stage}.BUCKET}
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploads/
            - suffix: .JPEG
          existing: true

